### ISSUE TITLE
Binance plugin searching beyond current time

### ISSUE THREAD

**Issue by Darkbladecr** [alpacahq/marketstore#100]
The Binance plugin currently will grab data from your query_start date, but then will overshoot the current time and then continue indefinitely, for example:
```
Jun 27 19:51:14 ip-172-31-1-100 marketstore[11903]: I0627 19:51:14.679280   11903 binancefeeder.go:241] Requesting BTC 2018-07-05 05:31:00 +0000 UTC - 2018-07-05 10:31:00 +0000 UTC
Jun 27 19:51:14 ip-172-31-1-100 marketstore[11903]: I0627 19:51:14.956699   11903 binancefeeder.go:251] len(rates) == 0
Jun 27 19:51:14 ip-172-31-1-100 marketstore[11903]: I0627 19:51:14.957102   11903 binancefeeder.go:241] Requesting ETH 2018-07-05 05:31:00 +0000 UTC - 2018-07-05 10:31:00 +0000 UTC
Jun 27 19:51:15 ip-172-31-1-100 marketstore[11903]: I0627 19:51:15.208399   11903 binancefeeder.go:251] len(rates) == 0
Jun 27 19:51:15 ip-172-31-1-100 marketstore[11903]: I0627 19:51:15.208787   11903 binancefeeder.go:241] Requesting LTC 2018-07-05 05:31:00 +0000 UTC - 2018-07-05 10:31:00 +0000 UTC
Jun 27 19:51:15 ip-172-31-1-100 marketstore[11903]: I0627 19:51:15.968124   11903 binancefeeder.go:251] len(rates) == 0
```

**Comment by dannyluong408** [comment]
+1 .. seems to never stop...

**Comment by dannyluong408** [comment]
Once it reaches the end it will keep trying to query and not actually
update the data until you restart the server/worker

**Comment by ethanchewy** [comment]
Yeah, thanks for clarifying!

Just fixed it in https://github.com/alpacahq/marketstore/pull/105:

This is how the plugin is supposed to work:
1) If a query_end not declared, the binancefeeder will continually get data forever
2) If a query_end is declared, the binancefeeder will stop at that time and continually retrieve query_end to query_end. This is expected behavior since this is a backgroundworker and works forever in the background.

**Comment by ethanchewy** [comment]
#105
